#ifndef GPSDataTypes_idl
#define GPSDataTypes_idl

#include "InterfaceDataTypes.idl"

module SplitMap{
    enum MapReturnStatus {
    // リクエストされたマップの位置をMapServerが何も保持していない場合
    INVALID_REQUEST;
    // リクエストされた範囲の中にMapServerが保持していない範囲が含まれているとき、
    // それを除いて保持している部分だけ返す場合
    RETURN_PARTIAL_MAP;

    // RETURN_VALUEを拡張
    // COMMON
    RETVAL_OK,
    RETVAL_INVALID_PARAMETER,
    RETVAL_EMPTY_MAP,
    RETVAL_INVALID_PRECONDITION,
    RETVAL_NOT_IMPL,
    RETVAL_UNKNOWN_ERROR,
    RETVAL_NOT_FOUND,
    RETVAL_ODOMETRY_INVALID_VALUE,
    RETVAL_ODOMETRY_TIME_OUT,
    RETVAL_RANGE_INVALID_VALUE,
    RETVAL_RANGE_TIME_OUT,
    RETVAL_EMERGENCY_STOP,
    RETVAL_OUTOF_RANGE
    };

    struct OGMapConfigEx {
        RTC::Pose2D globalPositionOfTopLeft; // 左上のグローバルな位置情報。
        double xScale; // スケール。位置画素の広さ。単位はm/pixel。
        double yScale; // yのスケール
        RTC::Size2D size; // マップのサイズ。widthとheight。単位はm
    };

    struct OGMapRequest {
        RTC::Pose2D globalPositionOfTopLeft;
        RTC::Size2D size;
    }

    struct OGMap {
        OGMapTile data; // マップの実際のデータ
        OGMapConfigEx config; // マップのコンフィグ
    };

    interface OGMapServerEX {
        MapReturnStatus requestLocalMap(
            in OGMapRequest map_request, out OGMap map
        );
    };
};



#endif